from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.sql import func
from APP.models.base import Base


class JobApplication(Base):
    __tablename__ = "job_applications"

    id = Column(Integer, primary_key=True, index=True)
    # Proper FK constraint referencing the users table
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False)
    job_title = Column(String, nullable=False)
    company_name = Column(String, nullable=False)
    job_description = Column(Text, nullable=True)

    # Tailored documents generated by Agent 3
    tailored_resume = Column(Text, nullable=True)
    tailored_cover_letter = Column(Text, nullable=True)

    match_score = Column(Integer, nullable=True)  # 0–100
    status = Column(String, default="draft", nullable=False)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
