"""
Job discovery and application tracking models.

DiscoveredJob — a raw job posting found by the Discovery Agent.
Application   — a job application derived from a discovered job, with tailoring results + status lifecycle.
"""

import enum

from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, JSON, Enum as SAEnum
from sqlalchemy.sql import func

from APP.models.base import Base


class ApplicationStatus(str, enum.Enum):
    """
    Lifecycle of a job application.
    Using str-enum so the value serialises cleanly to/from JSON and DB.
    """
    DISCOVERED = "discovered"       # Job found, not yet processed
    TAILORED = "tailored"           # Resume & cover letter generated
    SUBMITTED = "submitted"         # Application submitted (real or stub)
    INTERVIEWING = "interviewing"   # User manually updates after interview invite
    REJECTED = "rejected"           # Rejection received
    OFFERED = "offered"             # Offer received


class DiscoveredJob(Base):
    """
    A raw job posting returned by the Discovery Agent.
    Stored before any tailoring or application happens.
    """
    __tablename__ = "discovered_jobs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        String,
        ForeignKey("users.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )

    # Core job info
    title = Column(String, nullable=False)
    company = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    location = Column(String, nullable=True)

    # Where it came from
    source = Column(String, default="google_jobs")  # google_jobs | linkedin | indeed | gmail
    source_url = Column(String, nullable=True)

    # AI relevance score (0–100) assigned by Discovery Agent
    relevance_score = Column(Integer, nullable=True)

    discovered_at = Column(DateTime(timezone=True), server_default=func.now())


class Application(Base):
    """
    One application per discovered job.
    Tracks tailored documents, match score, and current lifecycle status.
    """
    __tablename__ = "applications"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        String,
        ForeignKey("users.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )
    job_id = Column(
        Integer,
        ForeignKey("discovered_jobs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Tailored documents generated by Resume Agent
    tailored_resume = Column(Text, nullable=True)
    tailored_cover_letter = Column(Text, nullable=True)
    tailored_summary = Column(Text, nullable=True)

    # AI assessment
    match_score = Column(Integer, nullable=True)          # 0–100
    missing_skills = Column(JSON, nullable=True)          # list[str]

    # Application lifecycle
    status = Column(
        SAEnum(ApplicationStatus),
        default=ApplicationStatus.DISCOVERED,
        nullable=False,
    )
    applied_at = Column(DateTime(timezone=True), nullable=True)   # set when submitted
    notes = Column(Text, nullable=True)                            # user notes

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
