"""
Resume version history model.

Every time the Resume Agent tailors a resume for a specific job,
a new ResumeVersion row is created — keeping a full audit trail of
all generated documents. The base resume (original upload) is also
stored here with application_id = NULL.
"""

from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, JSON
from sqlalchemy.sql import func

from APP.models.base import Base


class ResumeVersion(Base):
    """
    Immutable record of one resume version.

    - Raw upload (base):  application_id=NULL, version_tag="base"
    - Tailored version:   application_id=<app_id>, version_tag="<company>_<role>"
    """
    __tablename__ = "resume_versions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        String,
        ForeignKey("users.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )
    # NULL for the base resume; set for tailored versions
    application_id = Column(
        Integer,
        ForeignKey("applications.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Original raw text from PDF
    raw_text = Column(Text, nullable=True)

    # Structured profile extracted by Profile Agent (JSON dict)
    structured_data = Column(JSON, nullable=True)

    # Tailored content generated by Resume Agent
    tailored_resume = Column(Text, nullable=True)
    tailored_cover_letter = Column(Text, nullable=True)

    # Human-readable label, e.g. "google_swe_2025", "base"
    version_tag = Column(String, default="base", nullable=False)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
